spring.application.name=restaurant-erp

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=restaurant_db

server.port=8080

# JWT Configuration
app.jwtSecret=restaurant-erp-super-secret-key-change-this-in-production-use-environment-variable
app.jwtExpirationMs=86400000
