spring.application.name=restaurant-erp
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG


server.port=8080

# JWT Configuration
app.jwtSecret=restaurant-erp-super-secret-key-change-this-in-production-use-environment-variable
app.jwtAccessExpirationMs=900000
app.jwtRefreshExpirationMs=604800000
